name = "KiteModels"
uuid = "b94af626-7959-4878-9336-2adc27959007"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.5.2"

[deps]
AtmosphericModels = "c59cac55-771d-4f45-b14d-1c681463a295"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KitePodModels = "9de5dc81-f971-414a-927b-652b2f41c539"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
WinchModels = "7dcfa46b-7979-4771-bbf4-0aee0da42e1f"

[compat]
AtmosphericModels = "0.2"
BenchmarkTools = "1.2, 1.3"
Dierckx = "0.5"
DiffEqBase = "6.145"
DocStringExtensions = "0.8, 0.9"
Documenter = "0.27"
KitePodModels = "0.3"
KiteUtils = "0.5"
NLsolve = "4.5"
PackageCompiler = "2.0"
Parameters = "0.12"
PrecompileTools = "1.2"
Reexport = "1.2"
Rotations = "1.3"
StaticArrays = "1.9"
Sundials = "4.24"
WinchModels = "0.2"
julia = "1.9, 1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools", "Plots", "PackageCompiler", "Documenter"]
