name = "KiteModels"
uuid = "b94af626-7959-4878-9336-2adc27959007"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
KitePodSimulator = "558fcde3-b420-4fcf-b6fa-fc874c7e75b7"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6,1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
