[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KiteModels = "b94af626-7959-4878-9336-2adc27959007"
KitePodModels = "9de5dc81-f971-414a-927b-652b2f41c539"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"

[compat]
julia = "1.9, 1.10"
KiteUtils = "0.5"
KitePodModels = "0.3"
Documenter = "0.27"
